# Generated by Django 5.1.5 on 2025-07-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tujenge_app', '0003_contribution'),
        ('tujenge_app', '0004_auto_20250723_1603'),
    ]

    operations = [
    ]
